### ISSUE TITLE
Using `define/mock` requires definitions to happen in a specific order

### ISSUE THREAD

**Issue by logc** [jackfirth/racket-mock#40]
This does not prevent the use of `define/mock`, but it can require a developer to write first in the module procedures that are lower-level than the ones that require `define/mock`. 

For instance, let's imagine two functions `f` and `g`. `f` uses `g` to accomplish some side effect, like querying a remote server. We want `f` provided to the rest of modules, and `g` to be mocked during tests:

``` racket
#lang racket

(require mock)

(provide f)

(define (g x)
  "boo")

(define/mock (f x)
  #:mock g #:with-behavior (const "wow")
  (g x))

(module+ main
  (f 1))

(module+ test
  (f 2))
```

Now the real implementation of `g` is used on normal use of the module:

``` console
$ racket example.rkt
"boo"
```

And the mocked version of `g` is used on testing the module:

``` console
$ raco test example.rkt
raco test: (submod "example.rkt" test)
"wow"
```

However, switching the order in which `f` and `g` are written in the module leads to errors:

``` console
$ racket example.rkt
g: undefined;
 cannot reference an identifier before its definition
  in module: "/private/tmp/example.rkt"
  context...:
   /private/tmp/example.rkt: [running body]

$ raco test: (submod "example.rkt" test)
g: undefined;
 cannot reference an identifier before its definition
  in module: "/private/tmp/example.rkt"
  context...:
   /private/tmp/example.rkt: [running body]
   (submod /private/tmp/example.rkt test): [traversing imports]
   /Applications/Racket v6.5/share/pkgs/compiler-lib/compiler/commands/test.rkt:176:16
example.rkt: raco test: test raised an exception
```

If `f` is the provided function from this module, it would make sense to have it as the first definition in the module. `g` is "private identifier" of the module and should appear later on. Also, usually in Racket the order of definitions does not matter; must the use of `define/mock` take that convenience away?

**Comment by jackfirth** [comment]
Excellent find, I hadn't thought of this but the way the implementation works definitely causes this issue. When `define/mock` binds `f` to the "normal implementation" it expects each identifier named by a `#:mock` clause to be bound to a procedure because it uses those procedures to construct the normal implementation. They're not called until `f` is call though, so this should be fixable by wrapping each mocked procedure in a forwarding procedure that passes all arguments to it, delaying evaluation of the procedure.

**Comment by logc** [comment]
BTW, I wrote such a long example because I thought maybe it can be included in the documentation. I think there was another issue already about writing more examples ...

**Comment by logc** [comment]
Thanks for closing this issue so fast!

**Comment by jackfirth** [comment]
I think this is a clearer example than the ones that use `displayln` and `#:with-behavior void`, I'd like to replace the README and `define/mock` examples with it.
